"""
Module: demo_common
Description: Legacy re-exports from demo_layout and demo_utils.
New imports should use the sub-modules directly.
"""
from __future__ import annotations

__all__ = [
    "BOTTOM_BAR_H",
    "BOTTOM_BAR_Y",
    "CENTER_W",
    "CENTER_X",
    "COLOR_ACCENT",
    "COLOR_BG",
    "COLOR_BOTTOM_BAR_BG",
    "COLOR_DIVIDER",
    "COLOR_ERROR",
    "COLOR_GOLD",
    "COLOR_HIGHLIGHT",
    "COLOR_TEXT",
    "COLOR_TOP_BAR_BG",
    "FONT_LARGE",
    "FONT_MEDIUM",
    "FONT_SMALL",
    "LEFT_PANEL_W",
    "LEFT_PANEL_X",
    "LEFT_PANEL_Y",
    "PANEL_H",
    "PANEL_SIZE",
    "PANEL_W",
    "RIGHT_PANEL_W",
    "RIGHT_PANEL_X",
    "RIGHT_PANEL_Y",
    "TOP_BAR_H",
    "TOP_BAR_Y",
    "ErrorDisplay",
    "FrameThrottle",
    "SourceSurfaceManager",
    "build_default_sources",
    "draw_bottom_bar",
    "draw_bottom_bar_error",
    "draw_divider",
    "draw_histogram_bars",
    "draw_panel_border",
    "draw_save_notification",
    "draw_top_bar",
    "save_png",
]

from src.engine.scenes.demo_layout import (
    BOTTOM_BAR_H,
    BOTTOM_BAR_Y,
    CENTER_W,
    CENTER_X,
    COLOR_ACCENT,
    COLOR_BG,
    COLOR_BOTTOM_BAR_BG,
    COLOR_DIVIDER,
    COLOR_ERROR,
    COLOR_GOLD,
    COLOR_HIGHLIGHT,
    COLOR_TEXT,
    COLOR_TOP_BAR_BG,
    FONT_LARGE,
    FONT_MEDIUM,
    FONT_SMALL,
    LEFT_PANEL_W,
    LEFT_PANEL_X,
    LEFT_PANEL_Y,
    PANEL_H,
    PANEL_SIZE,
    PANEL_W,
    RIGHT_PANEL_W,
    RIGHT_PANEL_X,
    RIGHT_PANEL_Y,
    TOP_BAR_H,
    TOP_BAR_Y,
    draw_bottom_bar,
    draw_bottom_bar_error,
    draw_divider,
    draw_histogram_bars,
    draw_panel_border,
    draw_save_notification,
    draw_top_bar,
)
from src.engine.scenes.demo_utils import (
    ErrorDisplay,
    FrameThrottle,
    SourceSurfaceManager,
    build_default_sources,
    save_png,
)
