"""Generate the HUERFANAS_PERMITIDAS_EN set from the English catalog."""
import json
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent

with open(RAIZ / "locale" / "en.json", "r", encoding="utf-8") as f:
    en = json.load(f)

# All Spanish entries in en.json (inverse mappings)
spanish_entries = [k for k in en.keys() if any(c in k for c in 'áéíóúÁÉÍÓÚÑñ') or k in [
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
    'CONTINUAR', 'DEMO DE FILTROS', 'DEMO DE PATRONES', 'DEMO DE VISIÓN',
    'DEMOS ACADÉMICAS', 'FIN DE LA PARTIDA', 'JUGAR', 'LABORATORIO DE COLISIONES',
    'LABORATORIO DE INTERPOLACIÓN', 'LABORATORIO DE RUIDO', 'LABORATORIO DE TRANSFORMACIONES',
    'LABORATORIO DE VECTORES', 'MAPA MUNDIAL', 'MEZCLA ALFA', 'MODO LIBRE',
    'NO HAY ESCENARIOS', 'NO SE PUDO CARGAR EL ESCENARIO', 'PANEL DE PROGRESO',
    'PRIMEROS PASOS', 'RÉCORDS', 'TIENDA', 'ÁRBOL DE HABILIDADES', 'ASISTENTE DE ESCENARIOS',
]

print("HUERFANAS_PERMITIDAS_EN = {")
for k in sorted(set(spanish_entries)):
    print(f'    "{k}",')
print("}")