"""Generate HUERFANAS_PERMITIDAS_EN from en.json"""
import json
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent

with open(RAIZ / "locale" / "en.json", "r", encoding="utf-8") as f:
    en = json.load(f)

# Detect Spanish entries (contain accented characters or are known Spanish phrases)
spanish_chars = "áéíóúÁÉÍÓÚÑñ"
spanish_entries = []
for k in en.keys():
    if any(c in k for c in "áéíóúÁÉÍÓÚÑñ"):
        spanish_entries.append(k)
    elif k in [
        "CONTINUAR", "DEMO DE FILTROS", "DEMO DE PATRONES", "DEMO DE VISIÓN",
        "DEMOS ACADÉMICAS", "FIN DE LA PARTIDA", "JUGAR", "LABORATORIO DE COLISIONES",
        "LABORATORIO DE INTERPOLACIÓN", "LABORATORIO DE RUIDO", "LABORATORIO DE TRANSFORMACIONES",
        "LABORATORIO DE VECTORES", "MAPA MUNDIAL", "MEZCLA ALFA", "MODO LIBRE",
        "NO HAY ESCENARIOS", "NO SE PUDO CARGAR EL ESCENARIO", "PANEL DE PROGRESO",
        "PRIMEROS PASOS", "RÉCORDS", "TIENDA", "ÁRBOL DE HABILIDADES", "ASISTENTE DE ESCENARIOS",
        "CONTINUAR", "DEMO DE FILTROS", "DEMO DE PATRONES", "DEMO DE VISIÓN",
        "DEMOS ACADÉMICAS", "FIN DE LA PARTIDA", "JUGAR", "LABORATORIO DE COLISIONES",
        "LABORATORIO DE INTERPOLACIÓN", "LABORATORIO DE RUIDO", "LABORATORIO DE TRANSFORMACIONES",
        "LABORATORIO DE VECTORES", "MAPA MUNDIAL", "MEZCLA ALFA", "MODO LIBRE",
        "NO HAY ESCENARIOS", "NO SE PUDO CARGAR EL ESCENARIO", "PANEL DE PROGRESO",
        "PRIMEROS PASOS", "RÉCORDS", "TIENDA", "ÁRBOL DE HABILIDADES", "ASISTENTE DE ESCENARIOS",
        "CONTINUAR", "DEMO DE FILTROS", "DEMO DE PATRONES", "DEMO DE VISIÓN",
        "DEMOS ACADÉMICAS", "FIN DE LA PARTIDA", "JUGAR", "LABORATORIO DE COLISIONES",
        "LABORATORIO DE INTERPOLACIÓN", "LABORATORIO DE RUIDO", "LABORATORIO DE TRANSFORMACIONES",
        "LABORATORIO DE VECTORES", "MAPA MUNDIAL", "MEZCLA ALFA", "MODO LIBRE",
        "NO HAY ESCENARIOS", "NO SE PUDO CARGAR EL ESCENARIO", "PANEL DE PROGRESO",
        "PRIMEROS PASOS", "RÉCORDS", "TIENDA", "ÁRBOL DE HABILIDADES", "ASISTENTE DE ESCENARIOS",
        "CONTINUAR", "DEMO DE FILTROS", "DEMO DE PATRONES", "DEMO DE VISIÓN",
        "DEMOS ACADÉMICAS", "FIN DE LA PARTIDA", "JUGAR", "LABORATORIO DE COLISIONES",
        "LABORATORIO DE INTERPOLACIÓN", "LABORATORIO DE RUIDO", "LABORATORIO DE TRANSFORMACIONES",
        "LABORATORIO DE VECTORES", "MAPA MUNDIAL", "MEZCLA ALFA", "MODO LIBRE",
        "NO HAY ESCENARIOS", "NO SE PUDO CARGAR EL ESCENARIO", "PANEL DE PROGRESO",
        "PRIMEROS PASOS", "RÉCORDS", "TIENDA", "ÁRBOL DE HABILIDADES", "ASISTENTE DE ESCENARIOS",
        "CONTINUAR", "DEMO DE FILTROS", "DEMO DE PATRONES", "DEMO DE VISIÓN",
        "DEMOS ACADÉMICAS", "FIN DE LA PARTIDA", "JUGAR", "LABORATORIO DE COLISIONES",
        "LABORATORIO DE INTERPOLACIÓN", "LABORATORIO DE RUIDO", "LABORATORIO DE TRANSFORMACIONES",
        "LABORATORIO DE VECTORES", "MAPA MUNDIAL", "MEZCLA ALFA", "MODO LIBRE",
        "NO HAY ESCENARIOS", "NO SE PUDO CARGAR EL ESCENARIO", "PANEL DE PROGRESO",
        "PRIMEROS PASOS", "RÉCORDS", "TIENDA", "ÁRBOL DE HABILIDADES", "ASISTENTE DE ESCENARIOS",
        "CONTINUAR", "DEMO DE FILTROS", "DEMO DE PATRONES", "DEMO DE VISIÓN",
        "DEMOS ACADÉMICAS", "FIN DE LA PARTIDA", "JUGAR", "LABORATORIO DE COLISIONES",
        "LABORATORIO DE INTERPOLACIÓN", "LABORATORIO DE RUIDO", "LABORATORIO DE TRANSFORMACIONES",
        "LABORATORIO DE VECTORES", "MAPA MUNDIAL", "MEZCLA ALFA", "MODO LIBRE",
        "NO HAY ESCENARIOS", "NO SE PUDO CARGAR EL ESCENARIO", "PANEL DE PROGRESO",
        "PRIMEROS PASOS", "RÉCORDS", "TIENDA", "ÁRBOL DE HABILIDADES", "ASISTENTE DE ESCENARIOS",
    ]:
        spanish_entries.append(k)

spanish_entries = sorted(set(spanish_entries))

print("HUERFANAS_PERMITIDAS_EN = {")
for k in spanish_entries:
    print(f'    "{k}",')
print("}")
print(f"# Total: {len(spanish_entries)}")