#!/usr/bin/env python3
"""Regenerate the palette tables used by ``scripts/validate_assets.py``.

Why this script exists (AUD-011)
--------------------------------
``validate_assets.py`` carries the comment::

    # These are derived from the actual pixel data in the repository assets.
    # Run `python -m scripts.collect_palettes` to regenerate.

…but ``scripts/collect_palettes.py`` did not exist. So when the sprite art was
regenerated by ``tools/pixel_asset_generator.py`` under a new colour scheme, the
palette tables could not be refreshed and simply went stale. The validator then
failed on eight assets — a CI step that would have blocked every push, had CI
ever run (AUD-010).

The failure was NOT anti-aliasing noise, which is what it looked like at first.
``player_idle.png`` contains exactly six distinct colours — clean, deliberate
pixel art — and *none* of them appear in the declared player palette. The art is
fine; the table describing it was simply describing a previous generation of the
art. Snapping a million tileset pixels onto the stale palette, which is what a
naive "fix the assets" reading would have done, would have destroyed the
artwork to satisfy an out-of-date constraint.

This script closes that loop: it reads the current art and prints the table.

Usage
-----
    python scripts/collect_palettes.py                 # print the table
    python scripts/collect_palettes.py --max-colors 64 # flag over-rich assets
"""
from __future__ import annotations

import argparse
import fnmatch
import logging
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logger = logging.getLogger(__name__)

ASSETS_DIR = PROJECT_ROOT / "assets"

# Categories that are genuinely indexed pixel art and should be palette-locked.
# Tilesets are deliberately absent: assets/tilesets/tileset_stage0.png contains
# over 100,000 distinct colours, which means it is a rendered or rescaled image
# rather than hand-placed pixel art. A palette constraint cannot meaningfully
# describe it, so validate_assets.py checks tilesets for colour *count* instead.
# AUD-527 — `ui/*.png` dejó de cubrir el HUD entero: `heart_*.png` y
# `hud_frame.png` pasaron a degradado + antialiasing (decisión del dueño de
# modernizar el HUD, ver `docs/09_HUD_SPEC.md` §1), así que ya no son arte
# indexado — son el mismo caso que los tilesets, pintados en vez de
# paletizados a mano. `validate_assets.py` los mide por presupuesto de
# color (`COLOR_BUDGETS`), no por paleta fija. Lo que sigue aquí —retratos,
# reliquias, franja de escenario, flechas, la chispa de curación— sigue
# siendo pixel art indexado de verdad.
PALETTE_PATTERNS: tuple[str, ...] = (
    "sprites/player/*.png",
    "sprites/enemies/*.png",
    "sprites/bosses/*.png",
    "ui/portrait_*.png",
    "ui/relic_*.png",
    "ui/banner_*.png",
    "ui/menu_arrow.png",
    "ui/message_arrow.png",
)


def collect(pattern: str) -> tuple[set[tuple[int, int, int]], int]:
    """Every opaque colour used by assets matching ``pattern``."""
    from PIL import Image

    colors: set[tuple[int, int, int]] = set()
    files = 0
    for path in sorted(ASSETS_DIR.rglob("*.png")):
        rel = path.relative_to(ASSETS_DIR).as_posix()
        if not fnmatch.fnmatch(rel, pattern):
            continue
        files += 1
        img = Image.open(path).convert("RGBA")
        for r, g, b, a in img.getdata():
            if a > 0:
                colors.add((r, g, b))
    return colors, files


def report_rich_assets(max_colors: int) -> list[tuple[str, int]]:
    """Assets whose colour count exceeds a pixel-art-plausible ceiling."""
    from PIL import Image

    offenders = []
    for path in sorted(ASSETS_DIR.rglob("*.png")):
        img = Image.open(path).convert("RGBA")
        distinct = len({(r, g, b) for r, g, b, a in img.getdata() if a > 0})
        if distinct > max_colors:
            offenders.append((path.relative_to(ASSETS_DIR).as_posix(), distinct))
    return offenders


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-colors", type=int, default=0,
                        help="also report assets with more than N distinct colours")
    args = parser.parse_args(argv)

    print("SPRITE_PALETTES: list[tuple[str, set[tuple[int, int, int]]]] = [")
    for pattern in PALETTE_PATTERNS:
        colors, files = collect(pattern)
        if not files:
            continue
        print(f'    ("{pattern}", {{')
        ordered = sorted(colors)
        for i in range(0, len(ordered), 4):
            row = ", ".join(f"({r}, {g}, {b})" for r, g, b in ordered[i:i + 4])
            print(f"        {row},")
        print(f"    }}),  # {files} file(s), {len(colors)} colour(s)")
    print("]")

    if args.max_colors:
        offenders = report_rich_assets(args.max_colors)
        if offenders:
            logger.info("\n# Assets exceeding %d colours (not indexed pixel art):",
                        args.max_colors)
            for rel, n in offenders:
                logger.info("#   %-50s %7d colours", rel, n)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
