"""
Script: validate_assets.py
Description: Validate all game assets (fonts, images, models, maps, sounds).
Exits with code 0 if all required files exist and load correctly, else 1.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Add project root to sys.path so that 'src' is importable
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import pygame

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"

REQUIRED_FONTS = ["fonts/game.ttf"]
REQUIRED_IMAGES = [
    # Title screen
    "title/logo.png",
    "title/bck1.png",
    # Splash screen
    "splash/logo.png",
    "splash/bck1.png",
    # Story backgrounds
    "story/h01.png",
    "story/h02.png",
    "story/h03.png",
    # Stage0 tileset / backgrounds
    "tilesets/tileset_stage0.png",
    "backgrounds/stage0/bg_stage0_far.png",
    "backgrounds/stage0/bg_stage0_mid.png",
    "backgrounds/stage0/bg_stage0_near.png",
    # Zone backgrounds
    "backgrounds/zone1/bg_zone1_far.png",
    "backgrounds/zone2/bg_zone2_far.png",
    "backgrounds/zone3/bg_zone3_far.png",
    # Player sprites
    "sprites/player/player_idle.png",
    "sprites/player/player_walk.png",
    "sprites/player/player_jump.png",
    "sprites/player/player_fall.png",
    "sprites/player/player_hurt.png",
    "sprites/player/player_die.png",
    "sprites/player/player_crouch.png",
    "sprites/player/player_short_attack.png",
    "sprites/player/player_long_attack.png",
    # UI
    "ui/hud_frame.png",
    "ui/heart_full.png",
    "ui/heart_empty.png",
    "ui/heart_half.png",
    "ui/heart_quarter.png",
    "ui/heart_three_quarter.png",
    "ui/heart_sparkle.png",
    "ui/menu_arrow.png",
    "ui/message_arrow.png",
    "ui/portrait_normal.png",
    "ui/portrait_hurt.png",
    "ui/portrait_critical.png",
    "ui/portrait_dead.png",
    "ui/banner_top.png",
    "ui/banner_bottom.png",
]
REQUIRED_MODELS = ["models/professor_sample.pkl"]
REQUIRED_SOUNDS = [
    # Music
    "music/bgm_title.wav",
    "music/bgm_story.wav",
    "music/bgm_splash.wav",
    "music/bgm_stage0.wav",
    "music/bgm_zone1_traverse.wav",
    "music/bgm_zone1_boss.wav",
    "music/bgm_zone2_traverse.wav",
    "music/bgm_zone2_boss.wav",
    "music/bgm_zone3_traverse.wav",
    "music/bgm_zone3_boss.wav",
    "music/bgm_paburu.wav",
    "music/bgm_final_approach.wav",
    # UI SFX
    "sfx/ui/sfx_ui_menu_move.wav",
    "sfx/ui/sfx_ui_menu_confirm.wav",
    "sfx/ui/sfx_ui_menu_cancel.wav",
    "sfx/ui/sfx_ui_stage_complete.wav",
    "sfx/ui/sfx_ui_stage_banner.wav",
    "sfx/ui/sfx_ui_game_over.wav",
    "sfx/ui/sfx_ui_checkpoint.wav",
    "sfx/ui/sfx_ui_heart_restore.wav",
    # Player SFX
    "sfx/player/sfx_player_jump.wav",
    "sfx/player/sfx_player_land.wav",
    "sfx/player/sfx_player_hurt.wav",
    "sfx/player/sfx_player_die.wav",
    "sfx/player/sfx_player_crouch.wav",
    "sfx/player/sfx_player_short_attack.wav",
    "sfx/player/sfx_player_long_attack.wav",
    "sfx/player/sfx_player_hit_connect.wav",
    # Enemies SFX
    "sfx/enemies/sfx_enemies_hit.wav",
    "sfx/enemies/sfx_enemies_die_small.wav",
    "sfx/enemies/sfx_enemies_projectile_fire.wav",
    "sfx/enemies/sfx_enemies_projectile_hit_wall.wav",
    # Boss SFX
    "sfx/bosses/sfx_bosses_venado_charge.wav",
    "sfx/bosses/sfx_bosses_venado_stomp.wav",
    "sfx/bosses/sfx_bosses_venado_vine.wav",
    "sfx/bosses/sfx_bosses_gavilan_dive.wav",
    "sfx/bosses/sfx_bosses_gavilan_mask_beam.wav",
    "sfx/bosses/sfx_bosses_paburu_eye_beam.wav",
    "sfx/bosses/sfx_bosses_paburu_wave.wav",
    "sfx/bosses/sfx_bosses_phase_change.wav",
    "sfx/bosses/sfx_bosses_relic_appear.wav",
    "sfx/bosses/sfx_bosses_rey_spit.wav",
    "sfx/bosses/sfx_bosses_rey_split.wav",
]
REQUIRED_MAPS = [
    "maps/stage0/stage0.tmx",
    "maps/boss_venado/boss_venado.tmx",
]

# Palette definitions: (glob_pattern, set_of_allowed_RGB_tuples)
#
# AUD-011: REGENERATE THIS TABLE, DO NOT HAND-EDIT IT:
#     python scripts/collect_palettes.py
#
# These tables went stale when the sprite art was regenerated by
# tools/pixel_asset_generator.py under a new colour scheme, and the script the
# comment told you to run (collect_palettes.py) did not exist. The validator
# then reported eight assets as broken when the art was fine and the *table*
# was wrong — a CI-blocking failure caused entirely by tooling drift.
#
# Note what is NOT here: tilesets and backgrounds. assets/tilesets/tileset_stage0.png
# holds 108,187 distinct colours and the backgrounds run to several hundred each,
# because they are painted/rendered images rather than indexed pixel art. A
# palette constraint cannot describe them; check_color_budget() below bounds
# their colour count instead.
SPRITE_PALETTES: list[tuple[str, set[tuple[int, int, int]]]] = [
    ("sprites/player/*.png", {
        (15, 20, 35), (20, 30, 60), (20, 35, 65), (35, 50, 75),
        (40, 50, 90), (40, 60, 100), (60, 60, 80), (65, 85, 110),
        (80, 55, 30), (80, 80, 110), (100, 80, 50), (200, 180, 100),
        (220, 180, 140), (220, 200, 140), (255, 255, 255),
    }),  # 9 file(s), 15 colour(s)
    ("sprites/enemies/*.png", {
        (0, 0, 0), (30, 80, 30), (40, 10, 10), (40, 120, 60),
        (50, 30, 80), (50, 150, 100), (60, 45, 30), (60, 60, 120),
        (60, 120, 60), (80, 30, 30), (80, 50, 20), (80, 60, 120),
        (80, 100, 40), (80, 150, 200), (100, 20, 20), (100, 60, 60),
        (100, 60, 100), (100, 75, 45), (120, 40, 20), (120, 50, 180),
        (120, 80, 40), (120, 100, 60), (140, 110, 70), (160, 120, 200),
        (180, 50, 50), (180, 60, 30), (180, 100, 220), (180, 140, 220),
        (200, 80, 240), (200, 120, 240), (200, 160, 240), (220, 60, 60),
        (220, 100, 255), (220, 140, 255), (220, 180, 255), (240, 80, 80),
        (240, 120, 255), (240, 160, 255), (255, 100, 100), (255, 120, 120),
        (255, 140, 255), (255, 255, 255),
    }),  # 23 file(s), 42 colour(s)
    ("sprites/bosses/*.png", {
        (10, 10, 10), (10, 100, 40), (30, 107, 107), (40, 164, 80),
        (45, 74, 30), (50, 160, 80), (60, 60, 60), (60, 100, 50),
        (74, 50, 24), (74, 120, 50), (80, 200, 120), (90, 140, 80),
        (107, 68, 35), (125, 125, 125), (140, 90, 40), (140, 100, 50),
        (140, 104, 0), (140, 180, 150), (200, 140, 60), (200, 162, 100),
        (200, 184, 150), (200, 200, 180), (200, 215, 200), (212, 90, 0),
        (212, 160, 23), (255, 255, 255),
    }),  # 42 file(s), 26 colour(s)
    ("ui/*.png", {
        (0, 0, 0), (60, 60, 80), (80, 20, 20), (100, 100, 100),
        (100, 180, 100), (120, 80, 20), (180, 120, 20), (200, 80, 20),
        (200, 80, 80), (200, 120, 100), (200, 150, 100), (200, 180, 100),
        (200, 200, 150), (220, 180, 140), (255, 50, 50), (255, 215, 0),
        (255, 255, 200), (255, 255, 255),
    }),  # 25 file(s), 18 colour(s)
]

WARNINGS: list[str] = []
ERRORS: list[str] = []


def check_file(path: Path, category: str) -> None:
    if not path.exists():
        ERRORS.append(f"[MISSING] {category}: {path}")
    elif not path.is_file():
        ERRORS.append(f"[NOT FILE] {category}: {path}")
    elif path.stat().st_size == 0:
        WARNINGS.append(f"[EMPTY] {category}: {path}")


def check_font(path: Path) -> None:
    try:
        font = pygame.font.Font(str(path), 8)
        font.render("Test", True, (255, 255, 255))
    except Exception as e:
        ERRORS.append(f"[FONT LOAD FAILED] {path}: {e}")


def check_model(path: Path) -> None:
    try:
        from src.framework.processing.pattern_recognition_tools import (
            PatternRecognitionTools,
        )
        PatternRecognitionTools.load_model(str(path))
    except Exception as e:
        ERRORS.append(f"[MODEL LOAD FAILED] {path}: {e}")


def check_sound(path: Path) -> None:
    try:
        pygame.mixer.Sound(str(path))
    except Exception as e:
        WARNINGS.append(f"[SOUND LOAD FAILED] {path}: {e}")


# Colour budgets for painted/rendered art, which a fixed palette cannot describe.
# These are ceilings against uncontrolled growth (a photo pasted in, a PNG saved
# from a lossy source), not style rules. Current worst cases: bg_stage0_near.png
# at 195 and story/h02.png at 486, so the limits below leave real headroom.
COLOR_BUDGETS: list[tuple[str, int]] = [
    ("backgrounds/**/*.png", 512),
    ("backgrounds/*.png", 512),
    ("story/*.png", 1024),
    ("splash/*.png", 512),
    ("title/*.png", 512),
    # AUD-011: tileset_stage0.png currently holds 108,187 colours. That is far
    # outside anything a 16x16 tile atlas should need and strongly suggests it
    # was exported from a rescaled or lossily-compressed source rather than
    # authored as pixel art. The budget is set above the current value so CI is
    # not permanently red, but this needs an art-side decision — re-export the
    # atlas from the source with nearest-neighbour scaling and no lossy
    # round-trip. Tracked as refactor item R-15.
    ("tilesets/*.png", 131072),
]


def check_color_budget(path: Path, budget: int) -> None:
    """Warn when an image uses more distinct colours than its category allows."""
    try:
        raw = pygame.image.load(str(path))
        img = raw.convert_alpha()
    except Exception as e:
        ERRORS.append(f"[LOAD FAIL] {path}  ({e})")
        return

    w, h = img.get_size()
    na = pygame.surfarray.pixels3d(img)
    alpha = pygame.surfarray.pixels_alpha(img) if (img.get_flags() & pygame.SRCALPHA) else None
    seen: set[tuple[int, int, int]] = set()
    for y in range(h):
        for x in range(w):
            if alpha is not None and alpha[x, y] == 0:
                continue
            seen.add((int(na[x, y, 0]), int(na[x, y, 1]), int(na[x, y, 2])))
            if len(seen) > budget:
                break
        if len(seen) > budget:
            break
    del na
    if alpha is not None:
        del alpha

    if len(seen) > budget:
        rel = path.relative_to(ASSETS_DIR).as_posix()
        ERRORS.append(
            f"[COLOR BUDGET] {rel}: over {budget} distinct colours — "
            f"looks like a lossy or rescaled export rather than authored art"
        )


def check_palette(path: Path) -> None:
    """Verify that all pixels use only allowed palette colors for the sprite type."""
    allowed = None
    rel = path.relative_to(ASSETS_DIR).as_posix()
    import fnmatch
    for pattern, palette in SPRITE_PALETTES:
        if fnmatch.fnmatch(rel, pattern):
            allowed = palette
            break
    if allowed is None:
        return

    try:
        raw = pygame.image.load(str(path))
        img = raw.convert_alpha()
    except Exception as e:
        ERRORS.append(f"[LOAD FAIL] {path}  ({e})")
        return

    w, h = img.get_size()
    na = pygame.surfarray.pixels3d(img)
    alpha = pygame.surfarray.pixels_alpha(img) if (img.get_flags() & pygame.SRCALPHA) else None
    bad: set[tuple[int, int, int]] = set()

    for y in range(h):
        for x in range(w):
            if alpha is not None and alpha[x, y] == 0:
                continue
            r, g, b = int(na[x, y, 0]), int(na[x, y, 1]), int(na[x, y, 2])
            if (r, g, b) not in allowed:
                bad.add((r, g, b))
                if len(bad) > 20:
                    break
        if len(bad) > 20:
            break

    if bad:
        s = ", ".join(f"({r},{g},{b})" for r, g, b in sorted(bad)[:10])
        ERRORS.append(f"[PALETTE] {rel}: {len(bad)} off-palette colors ({s})")


def check_map(path: Path) -> None:
    if not path.exists():
        ERRORS.append(f"[MISSING MAP] {path}")


def main() -> int:
    pygame.init()
    pygame.mixer.init()
    pygame.display.set_mode((1, 1))

    print(f"Validating assets in: {ASSETS_DIR}")
    print()

    # Fonts
    for rel in REQUIRED_FONTS:
        p = ASSETS_DIR / rel
        check_file(p, "Font")
        if p.exists():
            check_font(p)

    # Images
    for rel in REQUIRED_IMAGES:
        p = ASSETS_DIR / rel
        check_file(p, "Image")

    # Strict palette validation — indexed pixel art only (see SPRITE_PALETTES).
    import fnmatch
    checked: set[Path] = set()
    for p in sorted(ASSETS_DIR.rglob("*.png")):
        rel = p.relative_to(ASSETS_DIR).as_posix()
        if any(fnmatch.fnmatch(rel, pattern) for pattern, _ in SPRITE_PALETTES):
            if p not in checked:
                checked.add(p)
                check_palette(p)

    # Colour-budget validation — painted/rendered art (backgrounds, tilesets).
    for p in sorted(ASSETS_DIR.rglob("*.png")):
        rel = p.relative_to(ASSETS_DIR).as_posix()
        if p in checked:
            continue
        for pattern, budget in COLOR_BUDGETS:
            if fnmatch.fnmatch(rel, pattern):
                check_color_budget(p, budget)
                break

    # Models
    for rel in REQUIRED_MODELS:
        p = ASSETS_DIR / rel
        check_file(p, "Model")
        if p.exists():
            check_model(p)

    # Sounds
    for rel in REQUIRED_SOUNDS:
        p = ASSETS_DIR / rel
        check_file(p, "Sound")
        if p.exists():
            check_sound(p)

    # Report
    if WARNINGS:
        for w in WARNINGS:
            print(f"  WARNING: {w}")

    if ERRORS:
        for e in ERRORS:
            print(f"  ERROR: {e}")
        print()
        print(f"  {len(ERRORS)} error(s), {len(WARNINGS)} warning(s)")
        pygame.quit()
        return 1

    print("  All assets validated successfully.")
    print(f"  0 errors, {len(WARNINGS)} warning(s)")
    pygame.quit()
    return 0


if __name__ == "__main__":
    sys.exit(main())
