"""
Script: validate_assets.py
Description: Validate all game assets (fonts, images, models, maps, sounds).
Exits with code 0 if all required files exist and load correctly, else 1.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Add project root to sys.path so that 'src' is importable
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import pygame

ASSETS_DIR = Path(__file__).resolve().parent.parent / "assets"

REQUIRED_FONTS = ["fonts/game.ttf"]
REQUIRED_IMAGES = [
    # Title screen
    "title/logo.png",
    "title/bck1.png",
    # Splash screen
    "splash/logo.png",
    "splash/bck1.png",
    # Story backgrounds
    "story/h01.png",
    "story/h02.png",
    "story/h03.png",
    # Stage0 tileset / backgrounds
    "tilesets/tileset_stage0.png",
    "backgrounds/stage0/bg_stage0_far.png",
    "backgrounds/stage0/bg_stage0_mid.png",
    "backgrounds/stage0/bg_stage0_near.png",
    # Zone backgrounds
    "backgrounds/zone1/bg_zone1_far.png",
    "backgrounds/zone2/bg_zone2_far.png",
    "backgrounds/zone3/bg_zone3_far.png",
    # Player sprites
    "sprites/player/player_idle.png",
    "sprites/player/player_walk.png",
    "sprites/player/player_jump.png",
    "sprites/player/player_fall.png",
    "sprites/player/player_hurt.png",
    "sprites/player/player_die.png",
    "sprites/player/player_crouch.png",
    "sprites/player/player_short_attack.png",
    "sprites/player/player_long_attack.png",
    # UI
    "ui/hud_frame.png",
    "ui/menu_arrow.png",
    "ui/message_arrow.png",
    "ui/portrait_normal.png",
    "ui/portrait_hurt.png",
    "ui/portrait_critical.png",
    "ui/portrait_dead.png",
    "ui/banner_top.png",
    "ui/banner_bottom.png",
]
# AUD-587 — antes se exigía `models/professor_sample.pkl`, un binario pickle
# que el validador mismo deserializaba para comprobarlo (con el aviso de
# «unpickling executes arbitrary code» de propina). El runtime ya entrena el
# modelo de referencia desde el dataset (F3.3), así que lo que se distribuye
# y se exige es el dataset, no el estimador.
REQUIRED_DATASETS = ["datasets/sample_dataset.npz"]
REQUIRED_SOUNDS = [
    # Music
    "music/bgm_title.wav",
    "music/bgm_story.wav",
    "music/bgm_splash.wav",
    "music/bgm_stage0.wav",
    "music/bgm_zone1_traverse.wav",
    "music/bgm_zone1_boss.wav",
    "music/bgm_zone2_traverse.wav",
    "music/bgm_zone2_boss.wav",
    "music/bgm_zone3_traverse.wav",
    "music/bgm_zone3_boss.wav",
    "music/bgm_paburu.wav",
    "music/bgm_final_approach.wav",
    # AUD-546 — una pista por fase del 4-1, material de autor. Llegaron
    # como `.mp3` (`resolver_pista_de_musica` ya las encuentra por ese
    # sufijo) y no como el par `.wav`/`.ogg` del resto de esta lista —
    # por eso la extensión aquí es la real, no la convención heredada.
    "music/bgm_stage4_1_fase1.mp3",
    "music/bgm_stage4_1_fase2.mp3",
    "music/bgm_stage4_1_fase3.mp3",
    "music/bgm_stage4_1_fase4.mp3",
    "music/bgm_stage4_1_fase5.mp3",
    "music/bgm_stage4_1_fase6.mp3",
    # AUD-575 — el tema en loop de la mina inundada (4-1b), material de
    # autor como las fases del cementerio: llegó como `.mp3` y se registra
    # con su extensión real, no la convención heredada.
    "music/4_1_b.mp3",
    # UI SFX
    "sfx/ui/sfx_ui_menu_move.wav",
    "sfx/ui/sfx_ui_menu_confirm.wav",
    "sfx/ui/sfx_ui_menu_cancel.wav",
    "sfx/ui/sfx_ui_stage_complete.wav",
    "sfx/ui/sfx_ui_stage_banner.wav",
    "sfx/ui/sfx_ui_game_over.wav",
    "sfx/ui/sfx_ui_checkpoint.wav",
    "sfx/ui/sfx_ui_heart_restore.wav",
    # Player SFX
    "sfx/player/sfx_player_jump.wav",
    "sfx/player/sfx_player_land.wav",
    "sfx/player/sfx_player_hurt.wav",
    "sfx/player/sfx_player_die.wav",
    "sfx/player/sfx_player_crouch.wav",
    "sfx/player/sfx_player_short_attack.wav",
    "sfx/player/sfx_player_long_attack.wav",
    "sfx/player/sfx_player_hit_connect.wav",
    # Enemies SFX
    "sfx/enemies/sfx_enemies_hit.wav",
    "sfx/enemies/sfx_enemies_die_small.wav",
    "sfx/enemies/sfx_enemies_projectile_fire.wav",
    "sfx/enemies/sfx_enemies_projectile_hit_wall.wav",
    # Boss SFX
    "sfx/bosses/sfx_bosses_venado_charge.wav",
    "sfx/bosses/sfx_bosses_venado_stomp.wav",
    "sfx/bosses/sfx_bosses_venado_vine.wav",
    "sfx/bosses/sfx_bosses_gavilan_dive.wav",
    "sfx/bosses/sfx_bosses_gavilan_mask_beam.wav",
    "sfx/bosses/sfx_bosses_paburu_eye_beam.wav",
    "sfx/bosses/sfx_bosses_paburu_wave.wav",
    "sfx/bosses/sfx_bosses_phase_change.wav",
    "sfx/bosses/sfx_bosses_relic_appear.wav",
    "sfx/bosses/sfx_bosses_rey_spit.wav",
    "sfx/bosses/sfx_bosses_rey_split.wav",
]

# Palette definitions: (glob_pattern, set_of_allowed_RGB_tuples)
#
# AUD-011: REGENERATE THIS TABLE, DO NOT HAND-EDIT IT:
#     python scripts/collect_palettes.py
#
# These tables went stale when the sprite art was regenerated by
# tools/pixel_asset_generator.py under a new colour scheme, and the script the
# comment told you to run (collect_palettes.py) did not exist. The validator
# then reported eight assets as broken when the art was fine and the *table*
# was wrong — a CI-blocking failure caused entirely by tooling drift.
#
# Note what is NOT here: tilesets and backgrounds. assets/tilesets/tileset_stage0.png
# holds 108,187 distinct colours and the backgrounds run to several hundred each,
# because they are painted/rendered images rather than indexed pixel art. A
# palette constraint cannot describe them; check_color_budget() below bounds
# their colour count instead.
SPRITE_PALETTES: list[tuple[str, set[tuple[int, int, int]]]] = [
    ("sprites/player/*.png", {
        (0, 0, 0), (2, 2, 8), (14, 14, 20), (18, 22, 38),
        (34, 40, 68), (38, 48, 86), (42, 28, 18), (42, 52, 92),
        (48, 58, 98), (54, 60, 92), (58, 70, 118), (60, 72, 122),
        (62, 42, 28), (68, 78, 122), (78, 86, 118), (78, 90, 148),
        (84, 96, 144), (90, 90, 100), (108, 120, 168), (110, 82, 48),
        (132, 112, 60), (160, 60, 60), (180, 140, 40), (180, 220, 255),
        (182, 162, 90), (188, 192, 210), (190, 135, 95), (192, 162, 92),
        (200, 200, 210), (220, 190, 120), (222, 224, 236), (235, 195, 150),
        (245, 210, 90), (255, 180, 180), (255, 255, 180), (255, 255, 255),
    }),  # 13 file(s), 36 colour(s)
    ("sprites/enemies/*.png", {
        (0, 0, 0), (0, 0, 2), (0, 0, 4), (0, 8, 50),
        (0, 40, 110), (0, 70, 20), (0, 72, 12), (0, 76, 26),
        (0, 82, 30), (0, 114, 154), (0, 154, 94), (2, 2, 6),
        (2, 2, 8), (2, 2, 12), (2, 6, 14), (2, 32, 92),
        (4, 4, 18), (4, 8, 16), (4, 36, 92), (4, 54, 4),
        (6, 8, 14), (6, 38, 94), (6, 86, 26), (6, 90, 40),
        (8, 8, 18), (8, 116, 48), (8, 128, 168), (8, 168, 108),
        (10, 14, 20), (10, 18, 60), (10, 20, 74), (10, 90, 40),
        (10, 96, 44), (12, 0, 0), (12, 12, 18), (12, 12, 72),
        (12, 52, 122), (12, 72, 12), (12, 122, 54), (14, 0, 0),
        (14, 14, 20), (14, 18, 26), (14, 22, 66), (14, 26, 60),
        (14, 54, 34), (14, 54, 124), (14, 84, 34), (14, 94, 34),
        (14, 96, 44), (14, 174, 114), (16, 16, 20), (16, 16, 26),
        (16, 46, 106), (18, 18, 26), (18, 18, 32), (18, 50, 106),
        (18, 68, 18), (18, 82, 32), (19, 69, 49), (20, 2, 0),
        (20, 20, 20), (20, 20, 24), (20, 104, 54), (20, 140, 180),
        (22, 20, 24), (22, 22, 32), (22, 36, 72), (22, 52, 26),
        (22, 52, 94), (22, 130, 62), (24, 4, 54), (24, 22, 26),
        (24, 32, 74), (24, 104, 54), (24, 110, 58), (26, 0, 0),
        (26, 8, 2), (26, 26, 32), (26, 26, 36), (26, 26, 86),
        (26, 36, 66), (26, 66, 136), (26, 86, 26), (26, 96, 46),
        (26, 96, 66), (26, 136, 68), (28, 0, 0), (28, 28, 32),
        (28, 28, 34), (28, 28, 38), (28, 36, 80), (28, 44, 90),
        (28, 58, 118), (28, 68, 48), (28, 108, 48), (28, 110, 58),
        (30, 22, 14), (30, 30, 44), (30, 62, 118), (30, 80, 30),
        (32, 0, 0), (32, 12, 72), (32, 16, 0), (32, 18, 4),
        (32, 32, 40), (32, 32, 46), (32, 52, 0), (32, 62, 38),
        (32, 96, 46), (32, 116, 66), (32, 122, 52), (33, 83, 63),
        (34, 8, 0), (34, 10, 62), (34, 16, 2), (34, 34, 44),
        (34, 34, 54), (34, 34, 94), (34, 50, 16), (34, 64, 38),
        (34, 84, 154), (34, 94, 34), (34, 142, 74), (36, 34, 38),
        (36, 44, 86), (36, 50, 86), (36, 70, 76), (36, 116, 66),
        (36, 122, 70), (36, 144, 76), (38, 16, 0), (38, 18, 68),
        (38, 20, 14), (38, 36, 40), (38, 38, 44), (38, 42, 52),
        (38, 58, 18), (38, 78, 148), (38, 108, 58), (38, 148, 80),
        (40, 10, 10), (40, 30, 20), (40, 40, 50), (40, 40, 60),
        (40, 48, 92), (40, 50, 80), (40, 60, 130), (40, 72, 60),
        (40, 80, 46), (40, 80, 60), (40, 120, 60), (40, 122, 70),
        (40, 140, 180), (40, 150, 82), (40, 200, 140), (40, 200, 240),
        (42, 16, 0), (42, 28, 14), (44, 14, 0), (44, 22, 0),
        (44, 28, 10), (44, 42, 46), (44, 44, 52), (44, 44, 58),
        (44, 52, 94), (44, 60, 26), (44, 108, 58), (45, 95, 75),
        (46, 0, 0), (46, 22, 74), (46, 26, 86), (46, 30, 10),
        (46, 60, 14), (46, 66, 6), (46, 76, 52), (46, 136, 66),
        (48, 22, 12), (48, 30, 16), (48, 48, 68), (48, 48, 108),
        (48, 62, 98), (48, 78, 52), (48, 108, 48), (48, 156, 88),
        (50, 30, 80), (50, 48, 52), (50, 150, 100), (52, 12, 12),
        (52, 12, 52), (52, 28, 2), (52, 30, 6), (52, 52, 62),
        (52, 56, 66), (52, 62, 92), (52, 64, 98), (52, 72, 32),
        (52, 92, 58), (52, 122, 92), (52, 162, 94), (54, 4, 4),
        (54, 24, 0), (54, 26, 2), (54, 34, 16), (54, 34, 94),
        (54, 36, 16), (54, 54, 64), (54, 64, 118), (54, 74, 14),
        (56, 30, 10), (56, 40, 22), (56, 42, 28), (56, 76, 30),
        (58, 26, 94), (58, 28, 0), (58, 28, 4), (58, 36, 10),
        (58, 36, 14), (58, 42, 22), (58, 56, 60), (58, 62, 74),
        (58, 72, 26), (58, 74, 40), (58, 88, 64), (58, 90, 78),
        (58, 148, 78), (60, 34, 24), (60, 36, 88), (60, 42, 28),
        (60, 45, 30), (60, 46, 12), (60, 60, 70), (60, 60, 80),
        (60, 60, 120), (60, 90, 64), (60, 90, 200), (60, 104, 112),
        (60, 120, 60), (61, 61, 71), (62, 34, 4), (62, 62, 70),
        (63, 63, 67), (64, 44, 26), (64, 46, 26), (64, 68, 78),
        (64, 84, 44), (66, 26, 26), (66, 26, 66), (66, 36, 12),
        (66, 44, 20), (66, 46, 28), (66, 82, 128), (66, 86, 40),
        (66, 106, 72), (66, 106, 126), (68, 0, 0), (68, 18, 18),
        (68, 38, 2), (68, 38, 8), (68, 40, 16), (68, 42, 22),
        (68, 48, 108), (68, 54, 40), (68, 68, 78), (68, 88, 28),
        (68, 148, 188), (69, 69, 79), (70, 38, 106), (70, 48, 22),
        (70, 48, 24), (70, 54, 36), (70, 68, 72), (70, 86, 52),
        (70, 140, 110), (71, 151, 101), (72, 24, 0), (72, 32, 0),
        (72, 48, 100), (72, 50, 24), (72, 52, 12), (72, 72, 82),
        (72, 76, 88), (72, 86, 40), (72, 92, 32), (72, 106, 112),
        (72, 122, 152), (73, 73, 79), (74, 0, 0), (74, 4, 4),
        (74, 34, 34), (74, 34, 74), (74, 60, 26), (74, 74, 82),
        (74, 74, 84), (75, 155, 95), (76, 48, 18), (76, 76, 84),
        (76, 80, 92), (78, 32, 10), (78, 46, 14), (78, 54, 28),
        (78, 56, 32), (78, 58, 40), (78, 60, 40), (78, 118, 84),
        (79, 79, 93), (80, 30, 30), (80, 40, 40), (80, 50, 20),
        (80, 50, 26), (80, 52, 28), (80, 60, 42), (80, 60, 120),
        (80, 62, 42), (80, 80, 90), (80, 100, 40), (80, 100, 54),
        (80, 140, 255), (80, 150, 200), (80, 220, 255), (80, 255, 120),
        (82, 2, 6), (82, 52, 16), (82, 54, 30), (82, 60, 36),
        (82, 62, 44), (82, 66, 48), (82, 102, 56), (83, 113, 155),
        (83, 191, 123), (84, 4, 4), (84, 4, 8), (84, 52, 120),
        (84, 54, 24), (84, 58, 34), (84, 62, 36), (84, 62, 40),
        (84, 88, 100), (84, 98, 52), (84, 104, 44), (84, 124, 144),
        (86, 46, 6), (86, 66, 26), (86, 86, 96), (86, 90, 106),
        (86, 130, 138), (86, 136, 166), (87, 87, 97), (88, 8, 8),
        (88, 18, 18), (88, 48, 48), (88, 48, 88), (88, 60, 30),
        (88, 74, 40), (88, 88, 96), (88, 88, 98), (88, 88, 108),
        (88, 108, 158), (90, 50, 10), (90, 70, 52), (90, 72, 52),
        (90, 85, 78), (90, 90, 100), (92, 46, 24), (92, 60, 28),
        (92, 62, 38), (92, 72, 54), (92, 112, 66), (94, 2, 6),
        (94, 40, 14), (94, 54, 14), (94, 66, 42), (94, 74, 34),
        (94, 94, 104), (95, 69, 59), (95, 77, 63), (95, 95, 155),
        (95, 125, 99), (95, 145, 215), (95, 155, 95), (96, 64, 132),
        (96, 66, 30), (96, 66, 36), (96, 74, 50), (96, 140, 148),
        (98, 18, 18), (98, 18, 22), (98, 68, 38), (98, 98, 106),
        (98, 118, 58), (98, 138, 158), (98, 148, 178), (100, 20, 20),
        (100, 30, 30), (100, 60, 60), (100, 60, 100), (100, 70, 36),
        (100, 75, 45), (100, 80, 30), (100, 86, 52), (100, 100, 108),
        (100, 100, 110), (100, 104, 120), (102, 106, 118), (103, 89, 75),
        (104, 58, 36), (105, 103, 107), (107, 83, 135), (108, 16, 20),
        (108, 68, 28), (108, 78, 42), (108, 80, 56), (108, 86, 62),
        (108, 88, 48), (108, 108, 118), (109, 79, 45), (110, 30, 30),
        (110, 30, 34), (110, 46, 12), (110, 80, 50), (110, 82, 58),
        (110, 110, 118), (110, 130, 70), (110, 150, 170), (112, 64, 40),
        (112, 110, 104), (112, 112, 122), (112, 116, 128), (112, 116, 132),
        (113, 153, 119), (114, 84, 54), (114, 94, 44), (114, 150, 156),
        (114, 172, 200), (115, 65, 65), (115, 95, 155), (115, 135, 75),
        (115, 255, 255), (116, 76, 36), (117, 101, 83), (118, 86, 54),
        (119, 97, 71), (120, 28, 32), (120, 40, 20), (120, 50, 180),
        (120, 66, 40), (120, 80, 30), (120, 80, 40), (120, 80, 45),
        (120, 90, 60), (120, 92, 68), (120, 100, 60), (120, 100, 80),
        (120, 120, 130), (120, 150, 220), (120, 200, 255), (120, 220, 210),
        (122, 92, 48), (123, 93, 59), (123, 127, 137), (124, 60, 26),
        (124, 84, 4), (124, 124, 132), (125, 107, 87), (126, 106, 56),
        (126, 126, 136), (127, 97, 73), (128, 88, 48), (128, 98, 68),
        (128, 108, 58), (128, 164, 170), (128, 186, 214), (131, 99, 167),
        (132, 2, 2), (132, 132, 140), (132, 190, 218), (134, 14, 4),
        (135, 95, 95), (135, 95, 135), (135, 105, 71), (135, 121, 87),
        (135, 135, 143), (136, 106, 62), (136, 130, 118), (136, 136, 144),
        (138, 138, 148), (140, 36, 36), (140, 50, 46), (140, 110, 70),
        (140, 110, 80), (140, 120, 70), (140, 140, 132), (140, 140, 150),
        (140, 176, 182), (142, 12, 2), (142, 146, 162), (143, 121, 97),
        (144, 24, 24), (144, 144, 152), (145, 185, 205), (146, 16, 16),
        (146, 204, 232), (147, 99, 75), (147, 151, 163), (148, 0, 6),
        (148, 28, 18), (148, 118, 74), (150, 20, 10), (150, 86, 52),
        (150, 110, 30), (150, 148, 142), (152, 22, 12), (154, 24, 24),
        (154, 54, 229), (154, 154, 146), (154, 154, 164), (155, 115, 75),
        (155, 135, 95), (155, 155, 165), (156, 26, 16), (156, 160, 176),
        (158, 38, 38), (158, 158, 166), (158, 216, 244), (160, 40, 30),
        (160, 40, 40), (160, 110, 100), (160, 110, 110), (160, 120, 200),
        (160, 140, 110), (162, 14, 20), (162, 42, 42), (164, 16, 22),
        (164, 34, 24), (164, 34, 34), (164, 44, 44), (164, 84, 104),
        (168, 38, 38), (168, 68, 243), (168, 168, 160), (168, 168, 178),
        (168, 172, 188), (170, 40, 30), (170, 40, 40), (170, 170, 178),
        (171, 171, 179), (172, 32, 32), (172, 42, 32), (172, 42, 42),
        (173, 173, 183), (174, 26, 32), (174, 34, 34), (174, 44, 44),
        (174, 54, 44), (174, 54, 54), (174, 64, 54), (174, 94, 94),
        (174, 154, 114), (174, 174, 154), (174, 174, 164), (175, 155, 105),
        (176, 106, 106), (178, 28, 28), (178, 30, 36), (178, 48, 38),
        (180, 50, 50), (180, 60, 30), (180, 60, 60), (180, 80, 255),
        (180, 100, 220), (180, 120, 40), (180, 130, 120), (180, 140, 220),
        (180, 150, 120), (180, 160, 40), (180, 160, 60), (180, 180, 172),
        (180, 180, 190), (180, 220, 160), (180, 255, 245), (182, 52, 52),
        (182, 82, 82), (183, 153, 109), (184, 54, 44), (184, 54, 54),
        (184, 164, 114), (184, 174, 144), (185, 121, 87), (186, 56, 56),
        (188, 58, 58), (188, 68, 68), (188, 78, 68), (188, 108, 108),
        (188, 188, 168), (188, 188, 178), (190, 42, 48), (190, 48, 48),
        (190, 60, 50), (190, 70, 64), (190, 70, 70), (190, 190, 198),
        (191, 195, 211), (192, 42, 42), (192, 152, 96), (193, 251, 255),
        (194, 44, 44), (194, 54, 34), (194, 64, 64), (194, 94, 94),
        (194, 124, 124), (198, 68, 58), (198, 68, 68), (198, 178, 128),
        (198, 188, 158), (198, 194, 184), (200, 70, 70), (200, 80, 70),
        (200, 80, 80), (200, 80, 240), (200, 90, 80), (200, 120, 120),
        (200, 120, 140), (200, 120, 240), (200, 150, 150), (200, 160, 240),
        (200, 180, 60), (200, 180, 140), (200, 185, 150), (200, 200, 180),
        (200, 200, 190), (200, 200, 220), (202, 202, 210), (203, 207, 223),
        (204, 124, 44), (204, 204, 196), (205, 205, 213), (208, 58, 58),
        (208, 68, 48), (208, 78, 78), (208, 108, 108), (208, 138, 138),
        (210, 70, 70), (210, 80, 70), (210, 80, 80), (210, 90, 90),
        (210, 150, 80), (210, 174, 138), (210, 190, 140), (210, 200, 170),
        (210, 206, 194), (214, 134, 134), (214, 214, 214), (215, 85, 85),
        (216, 216, 224), (218, 138, 58), (218, 218, 210), (219, 199, 149),
        (220, 40, 35), (220, 40, 40), (220, 60, 40), (220, 60, 60),
        (220, 70, 70), (220, 80, 60), (220, 90, 90), (220, 100, 255),
        (220, 120, 120), (220, 140, 255), (220, 150, 150), (220, 180, 255),
        (220, 200, 170), (220, 220, 220), (220, 244, 255), (224, 188, 152),
        (224, 220, 208), (224, 220, 210), (225, 95, 85), (228, 148, 148),
        (228, 228, 228), (228, 228, 236), (229, 89, 69), (230, 150, 70),
        (230, 230, 222), (232, 192, 148), (232, 232, 224), (235, 105, 105),
        (235, 115, 115), (235, 125, 115), (236, 200, 160), (236, 200, 164),
        (236, 232, 220), (236, 232, 222), (240, 80, 80), (240, 120, 255),
        (240, 160, 160), (240, 160, 255), (240, 240, 240), (244, 244, 236),
        (244, 244, 240), (245, 105, 105), (245, 115, 115), (245, 125, 125),
        (245, 225, 175), (250, 250, 250), (255, 60, 60), (255, 100, 100),
        (255, 115, 95), (255, 120, 120), (255, 125, 125), (255, 140, 255),
        (255, 155, 155), (255, 185, 185), (255, 200, 60), (255, 220, 60),
        (255, 220, 80), (255, 220, 200), (255, 228, 60), (255, 255, 100),
        (255, 255, 180), (255, 255, 255),
    }),  # 264 file(s), 718 colour(s)
    ("sprites/bosses/*.png", {
        (0, 0, 0), (0, 74, 14), (0, 88, 28), (2, 2, 8),
        (4, 81, 81), (10, 10, 10), (10, 100, 40), (14, 14, 20),
        (14, 138, 54), (18, 95, 95), (19, 48, 4), (24, 134, 54),
        (28, 152, 68), (30, 107, 107), (33, 62, 18), (34, 34, 34),
        (34, 74, 24), (38, 148, 68), (40, 164, 80), (45, 74, 30),
        (48, 24, 0), (48, 48, 48), (48, 88, 38), (48, 94, 24),
        (50, 160, 80), (54, 174, 94), (60, 60, 60), (60, 100, 50),
        (62, 38, 12), (62, 108, 38), (64, 114, 54), (68, 188, 108),
        (74, 50, 24), (74, 120, 50), (78, 128, 68), (80, 200, 120),
        (81, 42, 9), (90, 140, 80), (95, 56, 23), (99, 99, 99),
        (107, 68, 35), (113, 113, 113), (114, 64, 14), (114, 74, 24),
        (114, 78, 0), (114, 154, 124), (125, 125, 125), (128, 78, 28),
        (128, 88, 38), (128, 92, 0), (128, 168, 138), (140, 90, 40),
        (140, 100, 50), (140, 104, 0), (140, 180, 150), (174, 114, 34),
        (174, 136, 74), (174, 158, 124), (174, 174, 154), (174, 189, 174),
        (186, 64, 0), (186, 134, 0), (188, 128, 48), (188, 150, 88),
        (188, 172, 138), (188, 188, 168), (188, 203, 188), (200, 78, 0),
        (200, 140, 60), (200, 148, 11), (200, 162, 100), (200, 184, 150),
        (200, 200, 180), (200, 215, 200), (212, 90, 0), (212, 160, 23),
        (229, 229, 229), (243, 243, 243), (255, 255, 255),
    }),  # 42 file(s), 79 colour(s)
    ("ui/portrait_*.png", {
        (0, 0, 0), (60, 60, 80), (100, 100, 100), (200, 80, 80),
        (200, 120, 100), (220, 180, 140), (255, 255, 255),
    }),  # 4 file(s), 7 colour(s)
    ("ui/relic_*.png", {
        (0, 0, 0), (100, 180, 100), (200, 150, 100), (200, 200, 150),
        (255, 215, 0), (255, 255, 255),
    }),  # 5 file(s), 6 colour(s)
    ("ui/banner_*.png", {
        (0, 0, 0), (200, 180, 100),
    }),  # 2 file(s), 2 colour(s)
    ("ui/menu_arrow.png", {
        (255, 215, 0), (255, 255, 255),
    }),  # 1 file(s), 2 colour(s)
    ("ui/message_arrow.png", {
        (255, 215, 0), (255, 255, 255),
    }),  # 1 file(s), 2 colour(s)
]
WARNINGS: list[str] = []
ERRORS: list[str] = []


def check_file(path: Path, category: str) -> None:
    if not path.exists():
        ERRORS.append(f"[MISSING] {category}: {path}")
    elif not path.is_file():
        ERRORS.append(f"[NOT FILE] {category}: {path}")
    elif path.stat().st_size == 0:
        WARNINGS.append(f"[EMPTY] {category}: {path}")


def check_font(path: Path) -> None:
    try:
        font = pygame.font.Font(str(path), 8)
        font.render("Test", True, (255, 255, 255))
    except Exception as e:
        ERRORS.append(f"[FONT LOAD FAILED] {path}: {e}")


def check_dataset(path: Path) -> None:
    """Comprueba un dataset de características sin ejecutar nada.

    AUD-587 — sustituye a `check_model`: `np.load(allow_pickle=False)` lee
    arrays puros y se niega a deserializar objetos, que es justo la
    propiedad que hacía peligroso exigir un `.pkl` en CI.
    """
    try:
        import numpy as np

        with np.load(str(path), allow_pickle=False) as data:
            if "X" not in data or "y" not in data:
                ERRORS.append(
                    f"[DATASET INCOMPLETE] {path}: faltan las claves X/y"
                )
            elif data["X"].shape[0] != data["y"].shape[0]:
                ERRORS.append(
                    f"[DATASET MISMATCH] {path}: X e y no tienen la misma "
                    f"longitud ({data['X'].shape[0]} vs {data['y'].shape[0]})"
                )
    except Exception as e:
        ERRORS.append(f"[DATASET LOAD FAILED] {path}: {e}")


#: Cabecera mágica esperada por extensión de audio.
#:
#: AUD-159 — siete ficheros `.ogg` de `assets/music/` eran **WAV** (empiezan
#: por `RIFF`). SDL se fía de la extensión, así que `pygame.mixer.music.load`
#: los rechazaba con «Not an Ogg Vorbis audio stream» y el escenario se jugaba
#: **en silencio**: `StageScene` sólo registra un aviso y sigue.
#:
#: Costó verlo porque el juego prefiere `.wav` y cae al `.ogg` sólo si no hay
#: `.wav`. De los siete, cuatro no tenían gemelo —`bgm_boss`, `bgm_zone1`,
#: `bgm_zone2`, `bgm_zone3`— y ésos eran los que sonaban a nada. Los otros
#: tres tienen al lado un `.wav` de 8 a 12 segundos que el generador de
#: assets produce como marcador de posición, así que el juego lleva meses
#: reproduciendo el marcador en vez de la pista de 60 s que hay en el `.ogg`.
CABECERAS_DE_AUDIO: dict[str, bytes] = {
    ".ogg": b"OggS",
    ".wav": b"RIFF",
}


def check_audio_format(path: Path) -> None:
    """Que la extensión diga la verdad sobre el contenido."""
    esperada = CABECERAS_DE_AUDIO.get(path.suffix.lower())
    if esperada is None:
        return
    try:
        cabecera = path.read_bytes()[:4]
    except OSError as exc:
        WARNINGS.append(f"[AUDIO UNREADABLE] {path}: {exc}")
        return
    if cabecera != esperada:
        real = next((ext for ext, magia in CABECERAS_DE_AUDIO.items()
                     if magia == cabecera), f"desconocido ({cabecera!r})")
        WARNINGS.append(
            f"[AUDIO EXTENSION LIES] {path}: la extensión dice "
            f"«{path.suffix}» y el contenido es {real}. SDL se fía de la "
            f"extensión, así que este fichero NO se puede reproducir."
        )


def check_sound(path: Path) -> None:
    """Comprueba que el archivo se pueda decodificar, si hay mezclador.

    Sin mezclador cada sonido produciría un aviso «mixer not initialized» —43
    en este proyecto—, y un informe con 43 avisos que no son problemas de los
    assets es un informe que se deja de leer. La ausencia de tarjeta de sonido
    se anuncia una vez, en `main`.
    """
    if not pygame.mixer.get_init():
        return
    try:
        pygame.mixer.Sound(str(path))
    except Exception as e:
        WARNINGS.append(f"[SOUND LOAD FAILED] {path}: {e}")


# Colour budgets for painted/rendered art, which a fixed palette cannot describe.
# These are ceilings against uncontrolled growth (a photo pasted in, a PNG saved
# from a lossy source), not style rules. Worst cases at the time of writing:
#   - story/h03.png at 196,988 and title/logo.png at 266,590: the splash/story/
#     title screens are painted 1448x1086 plates (AUD-105) — photo-range colour
#     counts are their nature, so the ceilings just document them.
#   - bg_aulas_near.png at 15,785: painted zone background from a student
#     delivery (AUD-106), the same class.
#   - bg_stage0_near.png at 195: the original indexed art the 512 budgets were
#     set for; those lower limits stay.
# The old 512/1024 budgets predate both replacements and flagged the delivered
# art as broken — a tooling-drift failure, not an art failure (AUD-011).
COLOR_BUDGETS: list[tuple[str, int]] = [
    ("backgrounds/**/*.png", 20000),
    ("backgrounds/*.png", 512),
    ("story/*.png", 300000),
    ("splash/*.png", 400000),
    ("title/*.png", 400000),
    # AUD-546 — mismo caso que la nota de `tileset_stage0.png` de abajo,
    # aplicado a una entrega concreta en vez del genérico `tilesets/*.png`:
    # `tileset_stage4_1_selva.png` (assets de autor generados por IA,
    # 1774×887 usados como un tileset de baldosa 16×16 vía Tiled) mide
    # 250.133 colores — muy por encima del techo general, y por el mismo
    # motivo que la nota de abajo documenta: un lienzo pintado/generado no
    # es paleta indexada, y forzarlo a la regla general lo marcaría como
    # roto sin que el arte lo esté. Entrada específica, no se sube el
    # techo genérico — el resto de `tilesets/*.png` sigue vigilado a
    # 131072.
    ("tilesets/tileset_stage4_1_selva.png", 300000),
    # AUD-011: tileset_stage0.png currently holds 108,187 colours. That is far
    # outside anything a 16x16 tile atlas should need and strongly suggests it
    # was exported from a rescaled or lossily-compressed source rather than
    # authored as pixel art. The budget is set above the current value so CI is
    # not permanently red, but this needs an art-side decision — re-export the
    # atlas from the source with nearest-neighbour scaling and no lossy
    # round-trip. Tracked as refactor item R-15.
    ("tilesets/*.png", 131072),
    # AUD-527 — el panel de 9-slice del HUD pasó de relleno plano a
    # degradado + antialiasing (decisión del dueño de modernizar el HUD).
    # Mide 77-149 colores hoy; 256 da margen para retocar el degradado sin
    # ser la barra libre de un tileset — sigue siendo un icono de unos
    # pocos píxeles, no arte pintado a pantalla completa.
    # AUD-535 — `heart_*.png` se retiró de aquí junto con los sprites: la
    # vida dejó de ser una fila de corazones y no queda arte que medir.
    ("ui/hud_frame.png", 256),
]


def check_color_budget(path: Path, budget: int) -> None:
    """Warn when an image uses more distinct colours than its category allows."""
    try:
        raw = pygame.image.load(str(path))
        img = raw.convert_alpha()
    except Exception as e:
        ERRORS.append(f"[LOAD FAIL] {path}  ({e})")
        return

    w, h = img.get_size()
    na = pygame.surfarray.pixels3d(img)
    alpha = pygame.surfarray.pixels_alpha(img) if (img.get_flags() & pygame.SRCALPHA) else None
    seen: set[tuple[int, int, int]] = set()
    for y in range(h):
        for x in range(w):
            if alpha is not None and alpha[x, y] == 0:
                continue
            seen.add((int(na[x, y, 0]), int(na[x, y, 1]), int(na[x, y, 2])))
            if len(seen) > budget:
                break
        if len(seen) > budget:
            break
    del na
    if alpha is not None:
        del alpha

    if len(seen) > budget:
        rel = path.relative_to(ASSETS_DIR).as_posix()
        ERRORS.append(
            f"[COLOR BUDGET] {rel}: over {budget} distinct colours — "
            f"looks like a lossy or rescaled export rather than authored art"
        )


def check_palette(path: Path) -> None:
    """Verify that all pixels use only allowed palette colors for the sprite type."""
    allowed = None
    rel = path.relative_to(ASSETS_DIR).as_posix()
    import fnmatch
    for pattern, palette in SPRITE_PALETTES:
        if fnmatch.fnmatch(rel, pattern):
            allowed = palette
            break
    if allowed is None:
        return

    try:
        raw = pygame.image.load(str(path))
        img = raw.convert_alpha()
    except Exception as e:
        ERRORS.append(f"[LOAD FAIL] {path}  ({e})")
        return

    w, h = img.get_size()
    na = pygame.surfarray.pixels3d(img)
    alpha = pygame.surfarray.pixels_alpha(img) if (img.get_flags() & pygame.SRCALPHA) else None
    bad: set[tuple[int, int, int]] = set()

    for y in range(h):
        for x in range(w):
            if alpha is not None and alpha[x, y] == 0:
                continue
            r, g, b = int(na[x, y, 0]), int(na[x, y, 1]), int(na[x, y, 2])
            if (r, g, b) not in allowed:
                bad.add((r, g, b))
                if len(bad) > 20:
                    break
        if len(bad) > 20:
            break

    if bad:
        s = ", ".join(f"({r},{g},{b})" for r, g, b in sorted(bad)[:10])
        ERRORS.append(f"[PALETTE] {rel}: {len(bad)} off-palette colors ({s})")


def check_map(path: Path) -> None:
    if not path.exists():
        ERRORS.append(f"[MISSING MAP] {path}")


def main() -> int:
    pygame.init()
    # El mezclador es opcional para validar: sólo hace falta si se van a
    # *reproducir* sonidos, y aquí únicamente se comprueban archivos. Sin esta
    # guarda, ejecutar el validador en una máquina sin tarjeta de sonido —una
    # VM, WSL, un contenedor— moría con un traceback de ALSA que no tiene nada
    # que ver con los assets. En CI funcionaba porque el workflow exporta
    # SDL_AUDIODRIVER=dummy; quien lo ejecutara desde su portátil sin ese
    # detalle recibía un error incomprensible sobre un script de validación de
    # imágenes (AUD-059).
    try:
        pygame.mixer.init()
    except pygame.error as exc:
        print(f"  (audio no disponible: {exc} — se validan los archivos igual)")
    pygame.display.set_mode((1, 1))

    print(f"Validating assets in: {ASSETS_DIR}")
    print()

    # Fonts
    for rel in REQUIRED_FONTS:
        p = ASSETS_DIR / rel
        check_file(p, "Font")
        if p.exists():
            check_font(p)

    # Images
    for rel in REQUIRED_IMAGES:
        p = ASSETS_DIR / rel
        check_file(p, "Image")

    # Strict palette validation — indexed pixel art only (see SPRITE_PALETTES).
    import fnmatch
    checked: set[Path] = set()
    for p in sorted(ASSETS_DIR.rglob("*.png")):
        rel = p.relative_to(ASSETS_DIR).as_posix()
        if any(fnmatch.fnmatch(rel, pattern) for pattern, _ in SPRITE_PALETTES):
            if p not in checked:
                checked.add(p)
                check_palette(p)

    # Colour-budget validation — painted/rendered art (backgrounds, tilesets).
    for p in sorted(ASSETS_DIR.rglob("*.png")):
        rel = p.relative_to(ASSETS_DIR).as_posix()
        if p in checked:
            continue
        for pattern, budget in COLOR_BUDGETS:
            if fnmatch.fnmatch(rel, pattern):
                check_color_budget(p, budget)
                break

    # Datasets (AUD-587: sustituye a la exigencia del modelo pickle)
    for rel in REQUIRED_DATASETS:
        p = ASSETS_DIR / rel
        check_file(p, "Dataset")
        if p.exists():
            check_dataset(p)

    # Sounds
    for rel in REQUIRED_SOUNDS:
        p = ASSETS_DIR / rel
        check_file(p, "Sound")
        if p.exists():
            check_sound(p)

    # AUD-159 — la extensión de TODO el audio, no sólo el de la lista de
    # requeridos: los cuatro ficheros que dejaban escenarios mudos no estaban
    # en `REQUIRED_SOUNDS`, y por eso el validador pasaba en verde mientras el
    # juego se jugaba en silencio.
    for p in sorted(ASSETS_DIR.rglob("*")):
        if p.is_file() and p.suffix.lower() in CABECERAS_DE_AUDIO:
            check_audio_format(p)

    # Report
    if WARNINGS:
        for w in WARNINGS:
            print(f"  WARNING: {w}")

    if ERRORS:
        for e in ERRORS:
            print(f"  ERROR: {e}")
        print()
        print(f"  {len(ERRORS)} error(s), {len(WARNINGS)} warning(s)")
        pygame.quit()
        return 1

    print("  All assets validated successfully.")
    print(f"  0 errors, {len(WARNINGS)} warning(s)")
    pygame.quit()
    return 0


if __name__ == "__main__":
    sys.exit(main())
